---
- name: symlink /usr/bin/python -> /usr/bin/python3
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
        if [ -f /usr/libexec/platform-python ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/libexec/platform-python /usr/bin/python; 
          ln --symbolic /usr/libexec/platform-python /usr/bin/python3; 
        fi
      become: true

- name: Base setup
  hosts: all
  remote_user: root
  vars_prompt:
    - name: username
      prompt: Active directory admin username?
      private: no
    - name: password
      prompt: Active directory admin password?

    - name: com_username
      prompt: nextcould username?
      private: no
    - name: com_password
      prompt: nextcould password?
  vars:
    enable_jails: [sshd]
    disable_selinux: true
    slides_path: slides
  roles:
    - fedora
    - specific_setup
    - lpp_machine
    - fail2ban
    - kiosk_machine    
